### ISSUE TITLE
Error: This doesn't look like a binary PGP packet (c=45)

### ISSUE THREAD

**Issue by LOLLeela** [BenoitZugmeyer/pass-web#7]
Hi All,

Pass-Web does not seem to like passwords stored with ASCII Armor. 
I get "Error: This doesn't look like a binary PGP packet (c=45)" when attempting to open them. Some pass tools seem to have made them ASCII armored, some not.

Is it possible to add support for both?

Thanks!
-Leela

**Comment by LOLLeela** [comment]
Here is the debug output

INFO: Server listening on http://127.0.0.1:3000/
DEBUG: Error: This doesn't look like a binary PGP packet (c=45)
    at PacketParser.parse_tag_and_len (/usr/lib/node_modules/pass-web/node_modules/kbpgp/lib/openpgp/parser.js:133:15)
    at PacketParser.parse_header (/usr/lib/node_modules/pass-web/node_modules/kbpgp/lib/openpgp/parser.js:64:12)
    at PacketParser.parse (/usr/lib/node_modules/pass-web/node_modules/kbpgp/lib/openpgp/parser.js:73:12)
    at MessageParser.parse_packet (/usr/lib/node_modules/pass-web/node_modules/kbpgp/lib/openpgp/parser.js:46:45)
    at MessageParser.parse (/usr/lib/node_modules/pass-web/node_modules/kbpgp/lib/openpgp/parser.js:40:28)
    at /usr/lib/node_modules/pass-web/node_modules/kbpgp/lib/openpgp/parser.js:191:57
    at Object.katch (/usr/lib/node_modules/pass-web/node_modules/pgp-utils/lib/util.js:210:13)
    at parse (/usr/lib/node_modules/pass-web/node_modules/kbpgp/lib/openpgp/parser.js:190:17)
    at Message._parse (/usr/lib/node_modules/pass-web/node_modules/kbpgp/lib/openpgp/processor.js:416:15)
    at /usr/lib/node_modules/pass-web/node_modules/kbpgp/lib/openpgp/processor.js:894:17

**Comment by LOLLeela** [comment]
Well here is a complete lack of anything to do with this language shines though, 

setting "return unbox({ raw: content", to "return unbox({ armored: content," makes the armored content work, while killing the non armored content, so can we capture the fail message and try armored when raw fails?

Sorry, I like fiddling some times.

**Comment by BenoitZugmeyer** [comment]
Thank you for the report. I'll see what I can do, but i'd be happy to see what you did, even if it is a work in progress :) feel free to send a pr.

**Comment by BenoitZugmeyer** [comment]
I released a new version to support armored files, let me know if it works for you!

**Comment by LOLLeela** [comment]
Working great!

I was telling myself I have to try and look at it this weekend and have more of a fiddle, Thank you very much.
